/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package morecode;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class App {
  
    public static void main(String[] args) {
      
        SwingUtilities.invokeLater(() -> {
            String studentNumber = JOptionPane.showInputDialog("Enter Student Number:");
            String name = JOptionPane.showInputDialog("Enter name:");
            String surname = JOptionPane.showInputDialog("Enter surname:");
            String email = JOptionPane.showInputDialog("Enter email:");
            String phoneNumber = JOptionPane.showInputDialog("Enter Phone Number:");
            int mark1 = Integer.parseInt(JOptionPane.showInputDialog("Enter Mark1:"));
            int mark2 = Integer.parseInt(JOptionPane.showInputDialog("Enter Mark2:"));
            int AssignmentMark = Integer.parseInt(JOptionPane.showInputDialog("Enter Assignment mark:"));
            int examMark = Integer.parseInt("Enter exam mark:");
            
            //Calculate DP status
            boolean dpStatus = ((mark1 + mark2 +AssignmentMark) /3) >= 40;
            
            //Calculate final mark
            double courseworkAverage = (mark1 + mark2 + AssignmentMark) /3;
            double finalMark = (courseworkAverage * 0.4) + (examMark * 0.6);
            
            //Display results
            String message = "Student Number:" + studentNumber + "\n"
                    + "Name: " + name + "" + surname + "\n"
                    + "Email: " + email + "\n"
                    + "Phone Number: " +phoneNumber + "\n"
                    + "Mark one: " + mark1 + "\n"
                    + "Mark two: " + mark2 + "\n"
                    + "Assignment mark: " + AssignmentMark + "\n"
                    + "DP status: " + (dpStatus ? "Achieved" : "Not Achieved") + "\n"
                    + "final Mark: " + finalMark;
            
            JOptionPane.showMessageDialog(null, message);
        
        
     
        });
        
    }
}